sudo: false

addons:
  apt_packages:
    - libgl1-mesa-dev
    - xorg-dev

language: go

env:
  - GO111MODULE=on

go:
  - 1.11.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -v -race ./...
